name: Build and Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Firebase
      run: npm install -g firebase-tools
    - name: Deploy to Firebase
      uses: firebase deploy --project my-website-2ff22
      env:
        FIREBASE_TOKEN: secrets.FIREBASE_TOKEN