name: Firebase Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    container: andreysenov/firebase-tools
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Deploy to Firebase
      run: firebase deploy --project my-website-2ff22 --token ${{ secrets.FIREBASE_TOKEN }}